name: BlackHat
description: Code is like a poem
meta_description: "believe in code efficiency & against complexity"
email: backhat.c@gmail.com

markdown: kramdown
#highlighter: pygments
#github does not support pygments now, change to rouge
highlighter: rouge
logo: false
paginate: 10
baseurl: /
#domain_name: 'wuzhenyu.com.cn'
gems: [jekyll-paginate]

# Details for the RSS feed generator
url: 'http://backhat-backhat.github.io'
author: 'Blackhat'

# sidebar settings
sidebar: true
sidebar-about-description: "backhat"
sidebar-avatar:

# SNS settings
github_username: backhat-backhat
